version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR started on $(date)
      - aws --version
      - echo Logging into Amazon ECR...
      - REPOSITORY_URI=931587181982.dkr.ecr.eu-central-1.amazonaws.com/pipeline # Set your ECR repository URI
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Setting image tag...
      - IMAGE_TAG=build-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) # Use a unique identifier for the image tag

  build:
    commands:
      - echo Building and tagging the Docker image on $(date)
      - echo Running 'mvn clean install'...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Tagging the Docker image...
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR started on $(date)
      - echo Pushing to repository...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Setting container name...
      - DOCKER_CONTAINER_NAME=cdcicontainer
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo Printing imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json